# This is a basic workflow to help you get started with Actions

name: CI
env:
  APP_name: "my test"
  Packege_name: "flask-ver-${{ github.sha }}"

on:
  push:
    branches: [ master ]

jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Git copy repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo Hello, world!

  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print VAR
        run: echo "APP name:${{ env.APP_name }}"
      - name: Print VAR2
        run: echo "Packege version - ${{ env.Packege_name }}"

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
